version: '3.9'

services:
  db:
    image: postgres:latest
    ports:
      - "32767:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      .env
#  test_db:
#    image: postgres:latest
#    ports:
#      - "32768:5432"
#    env_file:
#      .env.test

volumes:
  postgres_data: